package gameplay;
/**
 * this class is a weapon which extends Wieldable and has a high and
 * low which is randomly generated by the hit() method in Wieldables
 * @author Jazmin Vagha 16941106
 *
 */
public class Sword extends Wieldable 
{
	/**
	 * this method sets all the values for the sword
	 * @param description - this is the description which is given in the Entity class
	 * @param high - this is the highest number that can be generated for a weapon
	 * @param low - this is the lowest number that can be generated for a weapon
	 * @author Jazmin Vagha 16941106
	 */
	public Sword(String description, int high, int low) 
	{
		super(description, high, low);
	}

}
